### ISSUE TITLE
How does auth work?

### ISSUE THREAD

**Issue by Xiyuz** [Kresten/winston-papertrail-transport#16]
```typescript
const papertrailTransport = new PapertrailTransport({
  host: 'logsXXX.papertrailapp.com',
  port: XXXXX,
  ... auth?
});
```

The above works! I can feed this transport into what I am using it with (nest-winston) and it just works. Papertrail's documentation way doesn't though.

```typescript
    WinstonModule.forRoot({
      transports: [
        new winston.transports.Http({ // This HTTP transport way Papertrail docs says doesn't work...
          host: 'logs.collector.solarwinds.com',
          path: '/v1/log',
          auth: { username: '', password: 'my-pw' },
          ssl: true,
        }),
        papertrailTransport, // just works ❤️❤️❤️
      ],
    }),
```

So thank you for this. But it made me think, this way that works is like using the [Syslog](https://www.papertrail.com/help/configuring-centralized-logging-from-nodejs-apps/) way, which needs the host and port. But I didn't see implementation or references to syslog in the code. How does that work?

I also see [here](https://github.com/Kresten/winston-papertrail-transport/blob/321dea06d768222cb12bfdc9e2898e7ad9c686e2/index.ts#L181) is where the TLS things happen and you use the net API to make that TCP? connection. So my question is what is to prevent a bot to bruteforce the `port` and `host` and spam the Papertrail account, since there is no sort of auth field?

**Comment by Kresten** [comment]
This package borrows from [winston-papertrail](https://github.com/kenperkins/winston-papertrail) and [winston-syslog](https://github.com/winstonjs/winston-syslog), so it is setup the syslog way with host and port.

In the settings of Papertrail you are able to select Token/HTTP or Syslog, if you want to try out the provided http example from papertrail. You can also reject logs from unrecognized systems, so this is also a way around the question below.

> So my question is what is to prevent a bot to bruteforce the port and host and spam the Papertrail account, since there is no sort of auth field?

That's just the way syslog works. There’s no built-in authentication in syslog messages. But I'm pretty sure the protocol does not acknowledge if messages have been received or not, so in the case of brute-forcing the host and port, the attacker will not know which combination is a valid endpoint. An attacker could replay syslog messages from your machine, but this can be mitigated by using TSL encryption.
