### ISSUE TITLE
The package makes Mocha tests to hang after `PaperTrailTransport` instantiation. The signal on potential leaks?

### ISSUE THREAD

**Issue by WhereJuly** [Kresten/winston-papertrail-transport#2]
I use the transport and experience the following behavior in Mocha tests: my tests never exit as soon as I instantiate `PaperTrailTransport`.

According to [Mocha docs](https://boneskull.com/mocha-v4-nears-release/#mochawontforceexit)

> If the mocha process is still alive after your tests seem "done", then your tests have scheduled something to happen (asynchronously) and haven't cleaned up after themselves properly. Did you leave a socket open?

A [StackOverflow question](https://stackoverflow.com/questions/50372866/mocha-not-exiting-after-test) with some discussion FYI.

Here is the example test instantiating `PaperTrailTransport` that hangs:

``` javascript
'use strict';

const assert = require('chai').assert,
    { PapertrailTransport } = require('winston-papertrail-transport');

describe('PapertrailTransportTest', function() {

    it('Should instantiate the transport and make it visible the transport does not allow the test to exit', function() {

        const papertrailTransport = new PapertrailTransport({
            host: '<my-host-here>',
            port: <my-port-here>
        });

        assert.isTrue(true);

    });

});
```

When I use the genuine Winston transports there is no such issue. There was no the issue as well when I used the original [winston-papertrail](https://github.com/kenperkins/winston-papertrail) package.

@Kresten can you check if something is not cleaned up that makes Mocha to hang? This is a problem that blocks the package use in production.

**Comment by Kresten** [comment]
I just ran your test with the [`winston-papertrail`](https://github.com/kenperkins/winston-papertrail) package
```
'use strict';
const winston = require('winston');
const assert = require('chai').assert;
require('winston-papertrail').Papertrail;

describe('PapertrailTransportTest', function() {
    it('Should instantiate the transport and make it visible the transport does not allow the test to exit', function() {
        const papertrailTransport =  new winston.transports.Papertrail({
            host: 'host,
            port: port,
    });

        assert.isTrue(true);
    });
});
```
and I get exactly the same behavior. They both hang.

But mocha isn't responsible of closing the connection after tests anyway. You can use the `close()` function when you want the connection to be closed. So your test would work like this:

```
'use strict';

const assert = require('chai').assert,
    { PapertrailTransport } = require('winston-papertrail-transport');

describe('PapertrailTransportTest', function() {

    it('Should instantiate the transport and make it visible the transport does not allow the test to exit', function() {

        const papertrailTransport = new PapertrailTransport({
            host: 'host,
            port: port,
    });

        assert.isTrue(true);
        papertrailTransport.close()
    });

});

```

**Comment by WhereJuly** [comment]
> You can use the close() function when you want the connection to be closed.
@Kresten thanks a lot. That is good info.
