### ISSUE TITLE
Transport doesn't close on short-running script

### ISSUE THREAD

**Issue by ciscoheat** [Kresten/winston-papertrail-transport#8]
Hi, I have some scripts that will run for a very short time, but I'd still like to use Papertrail for logging. I've noticed that when the execution time is low, sometimes the transport doesn't close, and the script never exits.

At the end of the script (using a transpiler language):

```haxe
logger.on('close', paperTrailTransport.close);
Timer.delay(logger.close, 200);
```

200 ms is about the minimum I have to wait for the script to exit, but it may vary of course, and I don't really want to set an arbitrary delay. Do you have any ideas how to make this more robust?

**Comment by Kresten** [comment]
Hi, 
Sorry for the late response!
Do you have a small repro I can try out?

**Comment by ciscoheat** [comment]
I solved it by creating a function that calls `logger.end()` and returns a promise that the resolves on the `finish` event, so it should be fine now! Thanks for this library. :)
